services:
  app:
    image: 'info:tag'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    environment:
      - SKELETONSERVICE_SETTINGS=/app/skeletonservice/instance/config.cfg
      - AUTH_DISABLED=true
    volumes:
      - .:/app
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  postgres_data:
    driver: local